### ISSUE TITLE
Can you release your latest changes? I'm without working submenus at the moment.

### ISSUE THREAD

**Issue by Folatt** [mate-desktop/mate-themes#147]
It's difficult for me working on Eclipse and Firefox this way.

Thanks in advance,

Folatt RPG

**Comment by raveit65** [comment]
I'm sorry to say without posting important infos like distro and gtk+ version i can't answer your question :)
Maybe you think a theme does not depend on gtk+ version.
I'm so tiered that users are to lazy to type this infos if they post here (80% of reports are useless because of this reason). 

Btw. I've released new tarballs for 3.20 an 3.22 ;)

**Comment by Folatt** [comment]
My distro is Arch Bang, gtk version 3.22.2 and my theme is TraditionalOK.

It's still not working, so I'm gonig to assume it might not be the themes that are broken.

**Comment by raveit65** [comment]
Latest versions you can download from 
http://pub.mate-desktop.org/releases/themes/3.22/
There are high chances that archlinux firefox compiled with gtk3 is broken.
Here with ff-0.49 in fedora the submenus are fine.
